.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. reddcoin_qt test_reddcoin_qt
clean: FORCE
	$(MAKE) -C .. reddcoin_qt_clean test_reddcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_reddcoin_qt_check
reddcoin-qt reddcoin-qt.exe: FORCE
	 $(MAKE) -C .. reddcoin_qt
apk: FORCE
	$(MAKE) -C .. reddcoin_qt_apk
